name: aws-docker
on:
  push:
    branches: '**'

jobs:
  PublicaNaAWS:
    runs-on: [ estoqueinteligente, dev ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Cria Variáveis
        id: create_variables
        continue-on-error: true
        run: |
          branch=${{ github.ref }}
          branch=${branch/refs\/heads\//}
          repo=${{ github.repository }}
          repo=${repo/*\//}
          repo=${repo,,} # converte o nome do repositório para minúsculo

          echo $branch | tee branch.txt
          echo $repo | tee repo.txt
      
      - name: Atualiza imagem do app
        id: change_image
        run: |
          branch=$(cat branch.txt)
          repo=$(cat repo.txt)

          docker build -t ${repo}:${branch} .
      
          if docker inspect "${repo}_${branch}_a" >/dev/null 2>&1; then
            docker run -d --name ${repo}_${branch}_b ${repo}:${branch} -e "VIRTUAL_HOST=${branch}.${repo}.estoqueinteligente.projetonow.net" && \
            docker rm -f ${repo}_${branch}_a
            exit 0
          else
            docker run -d --name ${repo}_${branch}_a ${repo}:${branch} -e "VIRTUAL_HOST=${branch}.${repo}.estoqueinteligente.projetonow.net" && \
            docker rm -f ${repo}_${branch}_b || true
            exit 0
          fi