name: aws-docker
on:
  push:
    branches: '**'

jobs:
  PublicaNaAWS:
    runs-on: trabalessandra
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

#
#- name: Check if container exists 
#run: | if [ $(docker ps -q -f name=my_container) ]; then echo 'true' else echo 'false' 

#- name: Run job2 if container exists if: ${{ steps.check_container.outputs.status == 'true' }} 
#run: | echo 'Container exists, running job2' 

#job3: runs-on: ubuntu-latest needs: job1 if: ${{ steps.check_container.outputs.status == 'false' }} steps: - name: Run job3 run: | echo 'Container does not exist, running job3'



      - name: Verifica contêiner
        id: check_container
        run: |
          branch=${{ github.ref }}
          branch=${branch/refs\/heads\//}
          repo=${{ github.repository }}
          repo=${repo/*\//}
          repo=${repo,,} # converte o nome do repositório para minúsculo
          
          echo $branch | tee branch.txt
          echo $repo | tee repo.txt

          # Verifica se o contêiner existe
          if docker inspect "${repo}_${branch}_1" >/dev/null 2>&1; then
          echo "Container existente"
          exit 0
          else
          echo "Container não existente"
          exit 1
          fi
         
      - name: Configura nome do container, envia branch e repositório
        if: ${{ failure() }}
        run: |
            branch=$(cat branch.txt)
            repo=$(cat repo.txt)

            sed -i "s/REPO/${repo}/g" docker-compose.yml
            sed -i "s/BRANCH/${branch}/g" docker-compose.yml  
            
      - name: Builda e sobe o container
        if: ${{ failure() }}
        run: docker-compose up -d --build #--force-recreate
        shell: bash

      - name: Configura NGINX
        if: ${{ failure() }}
        run: |
            branch=$(cat branch.txt)
            repo=$(cat repo.txt)

            PORTA=$(docker-compose port ${repo}_${branch} 80| cut -d: -f2)
            
            # Define o caminho do arquivo de configuração do NGINX
            config_file="/etc/nginx/sites-enabled/${branch}.conf"

            # Lê o modelo de configuração do NGINX para uma variável
            template=$(cat /etc/nginx/sites-available/template-trabalessandra.conf)

            # Substitui as variáveis no modelo de configuração com as informações corretas
            template=$(echo $template | sed -r "s/BRANCH/$branch/")
            template=$(echo $template | sed -r "s/PORTA/$PORTA/")

            # Cria o novo arquivo de configuração com as informações atualizadas
            echo "$template" | sudo tee > $config_file
            
      - name: Recarrega NGINX
        if: ${{ failure() }}
        run: /usr/sbin/nginx -s reload
      


