name: Branch Deleted
on:
    delete: 
jobs: 
    build: 
        runs-on: trabalessandra 
        steps: 
            - name: Checkout 
              uses: actions/checkout@v2 
            
            - name: Get Branch Name 
              run: echo ${{ github.ref }}
              
