name: notebook-docker
on:
  push:
    branches: [main]

jobs:
  Run:
    strategy:
      matrix:
        runs-on: [notebook, trabalessandra]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Bash Action
        run: docker-compose up -d --build --remove-orphans #--force-recreate
        shell: bash
        
      - name: Bash Action
        run: docker-compose port app 80
        shell: bash
