name: notebook-docker
on:
  push:
    branches: [main]

jobs:
  Build:
    runs-on:  notebook
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          # registry: 
          # Username used to log against the Docker registry
          username: ${{ secrets.DOCKERHUB_USER }}
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.DOCKERHUB_PASS }}
      
      - name: Build and push Docker images
        uses: docker/build-push-action@v4.0.0
        with:
           context: .
           push: true
           tags: |
            ncmbjr/teste:v1
            ncmbjr/teste:latest
  Run:
    runs-on: notebook
    steps:
      - name: Docker Compose Action
        uses: isbang/compose-action@v1.4.1
        with:
          up-flags: --detach
    # relative path to compose file(s)
    #compose-file: # optional, default is ./docker-compose.yml
    # additional options to pass to `docker-compose` command
    #compose-flags: # optional, default is 
    # additional options to pass to `docker-compose down` command
    #down-flags: # optional, default is 
    # services to perform docker-compose up
    #services: # optional
    # additional options to pass to `docker-compose up` command
     
      
      #- name: Docker Login
        #uses: docker/login-action@v2.1.0
        #with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          #registry: # optional
          # Username used to log against the Docker registry
          #username: ${{ secret.ECR_USER }}
          # Password or personal access token used to log against the Docker registry
          #password: ${{ secret.ECR_USER }}
