name: notebook-docker
on:
  push:
    branches: [main]

jobs:
  Build:
    runs-on:  notebook
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          # registry: 
          # Username used to log against the Docker registry
          username: ${{ secrets.DOCKERHUB_USER }}
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.DOCKERHUB_PASS }}
      
      - name: Build and push Docker images
        uses: docker/build-push-action@v4.0.0
        with:
           context: .
           push: true
           tags: |
            ncmbjr/teste:v2
            ncmbjr/teste:latest
  Run:
    runs-on: [notebook, trabalessandra]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Bash Action
        run: docker-compose up -d --build --remove-orphans #--force-recreate # optional, default is greet
        shell: bash
