name: notebook-docker
on:
  push:
    branches: '**'

jobs:
  Run:
    strategy:
      matrix:
        runs-on: [notebook, trabalessandra]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Builda e sobe o container
        run: docker-compose up -d --build --remove-orphans #--force-recreate
        shell: bash
        
      - name: Configura NGINX
        run: |
            branch=${{ github.ref }}
            branch=${branch/refs\/heads\//}
            PORTA=$(docker-compose port app 80| cut -d: -f2)
            
            
            # Define o caminho do arquivo de configuração do NGINX
            config_file="/etc/nginx/sites-enabled/${branch}.conf"

            # Lê o modelo de configuração do NGINX para uma variável
            template=$(cat /etc/nginx/sites-available/template-trabalessandra.conf)

            # Substitui as variáveis no modelo de configuração com as informações corretas
            template=$(echo $template | sed -r "s/BRANCH/$branch/")
            template=$(echo $template | sed -r "s/PORTA/$PORTA/")${{ env.PORTA }}}

            # Cria o novo arquivo de configuração com as informações atualizadas
            echo "$template" | sudo tee > $config_file
            
      - name: Configura NGINX
        run: /usr/sbin/nginx -s reload
      

