name: notebook-docker
on:
  push:
    branches: '**'

jobs:
  Compose:
    runs-on: notebook
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Builda e sobe o container
        run: docker-compose up -d --build --remove-orphans #--force-recreate
        shell: bash

