name: notebook-docker
on:
  push:
    branches: [main]

jobs:
  Run:
    strategy:
      matrix:
        runs-on: [notebook, trabalessandra]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Bash Action
        run: docker-compose up -d --build --remove-orphans #--force-recreate
        shell: bash
        
      - name: Bash Action
        run: PORTA=$(docker-compose port app 80)
        shell: bash
        
      - name: Configurar NGINX
        run: |
            # Define o caminho do arquivo de configuração do NGINX
            config_file="/etc/nginx/sites-enabled/${{ github.ref }}.conf"

            # Lê o modelo de configuração do NGINX para uma variável
            template=$(cat /etc/nginx/sites-available/template-trabalessandra.conf)

            # Substitui as variáveis no modelo de configuração com as informações corretas
            template=${template//\${branch}/${{ github.ref }}}
            template=${template//\${porta}/${{ env.PORTA }}}

            # Cria o novo arquivo de configuração com as informações atualizadas
            echo "$template" | sudo tee > $config_file
      

